"""Remove domain field from word_definitions table

Revision ID: 368072c06329
Revises: f0af0fd0ed3b
Create Date: 2025-10-09 12:26:38.953299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368072c06329'
down_revision = 'f0af0fd0ed3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_contexts', schema=None) as batch_op:
        batch_op.drop_column('default_domain')

    with op.batch_alter_table('word_definitions', schema=None) as batch_op:
        batch_op.drop_column('domain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', mysql.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('language_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_domain', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
